name: Compilar APK de Despertador

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Encontrar carpeta del proyecto y dar permisos a Gradle
      run: |
        GRADLEW_PATH=$(find . -name "gradlew" -print -quit)
        PROJECT_DIR=$(dirname "$GRADLEW_PATH")
        echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV
        chmod +x "$GRADLEW_PATH"

    - name: Compilar la aplicacion en modo Debug
      run: |
        cd ${{ env.PROJECT_DIR }}
        ./gradlew assembleDebug

    - name: Guardar el archivo APK resultante
      uses: actions/upload-artifact@v4
      with:
        name: Despertador-APK
        path: |
          **/build/outputs/apk/debug/app-debug.apk
