name: Compilar APK de Despertador

on:
  push:
    branches: [ main, master ] # Se ejecuta cuando subes cambios a tu rama principal
  workflow_dispatch: # Esto te permite activar la compilación manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Dar permisos de ejecucion a Gradle
      run: chmod +x ./gradlew

    - name: Compilar la aplicacion en modo Debug
      run: ./gradlew assembleDebug

    - name: Guardar el archivo APK resultante
      uses: actions/upload-artifact@v4
      with:
        name: Despertador-APK
        path: app/build/outputs/apk/debug/app-debug.apk
